//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL03_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int maoder { get; set; }
        public Nullable<int> masach { get; set; }
        public Nullable<int> madocgia { get; set; }
        public Nullable<System.DateTime> ngaymua { get; set; }
        public Nullable<int> maadmin { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual docgia docgia { get; set; }
        public virtual sach sach { get; set; }
    }
}
