//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL03_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sach()
        {
            this.giohangs = new HashSet<giohang>();
            this.orders = new HashSet<order>();
        }
    
        public int masach { get; set; }
        public string tensach { get; set; }
        public int namxb { get; set; }
        public int manxb { get; set; }
        public int matheloai { get; set; }
        public int matacgia { get; set; }
        public int soluong { get; set; }
        public string ghichu { get; set; }
        public string khusach { get; set; }
        public int giatien { get; set; }
        public byte[] dataanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giohang> giohangs { get; set; }
        public virtual nxb nxb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        public virtual tacgia tacgia { get; set; }
        public virtual theloai theloai { get; set; }
    }
}
