//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL03_DAL.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accountt()
        {
            this.connects = new HashSet<connect>();
            this.docgias = new HashSet<docgia>();
            this.nhanviennhasaches = new HashSet<nhanviennhasach>();
        }
    
        public int ID_User { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string Gmail { get; set; }
        public Nullable<int> ID_Position { get; set; }
        public string Salt { get; set; }
    
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<connect> connects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<docgia> docgias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhanviennhasach> nhanviennhasaches { get; set; }
    }
}
