//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL03_DAL.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int maadmin { get; set; }
        public Nullable<int> ID_Users { get; set; }
    }
}
