//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL03_DAL.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class connect
    {
        public int ID_connect { get; set; }
        public Nullable<int> masach { get; set; }
        public Nullable<int> madocgia { get; set; }
        public Nullable<int> manhanvien { get; set; }
        public Nullable<System.DateTime> thoigiangiaodich { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> soluongmua { get; set; }
        public Nullable<int> tongtien { get; set; }
    
        public virtual accountt accountt { get; set; }
        public virtual sach sach { get; set; }
    }
}
