//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL03_DAL.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNS : DbContext
    {
        public QLNS()
            : base("name=QLNS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountt> accountts { get; set; }
        public virtual DbSet<admin> adminS { get; set; }
        public virtual DbSet<connect> connects { get; set; }
        public virtual DbSet<docgia> docgias { get; set; }
        public virtual DbSet<giohang> giohangs { get; set; }
        public virtual DbSet<nhanviennhasach> nhanviennhasaches { get; set; }
        public virtual DbSet<nxb> nxbs { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<sach> saches { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tacgia> tacgias { get; set; }
        public virtual DbSet<theloai> theloais { get; set; }
    }
}
